.PHONY: clean All

All:
	@echo "----------Building project:[ Sec6_Challenge - Debug ]----------"
	@cd "Sec6_Challenge" && "$(MAKE)" -f  "Sec6_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Sec6_Challenge - Debug ]----------"
	@cd "Sec6_Challenge" && "$(MAKE)" -f  "Sec6_Challenge.mk" clean
