.PHONY: clean All

All:
	@echo "----------Building project:[ Sec7_Challenge - Debug ]----------"
	@cd "Sec7_Challenge" && "$(MAKE)" -f  "Sec7_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Sec7_Challenge - Debug ]----------"
	@cd "Sec7_Challenge" && "$(MAKE)" -f  "Sec7_Challenge.mk" clean
