.PHONY: clean All

All:
	@echo "----------Building project:[ Section5_Exc1 - Debug ]----------"
	@cd "Section5_Exc1" && "$(MAKE)" -f  "Section5_Exc1.mk"
clean:
	@echo "----------Cleaning project:[ Section5_Exc1 - Debug ]----------"
	@cd "Section5_Exc1" && "$(MAKE)" -f  "Section5_Exc1.mk" clean
